### ISSUE TITLE
Dressrosa S30 file rename

### ISSUE THREAD

**Issue by tajlamont** [SpykerNZ/one-pace-for-plex#1]
I'm on Windows and I'm using the .exe file to rename the mkvs. It worked for the 3 other seasons of One Pace I have (27, 28, 29) but it does not seem to work for Dressrosa. I previously ran rename.exe before I downloaded Dressrosa so I'm not sure if that has anything to do with it or not.

**Comment by SpykerNZ** [comment]
Just had a quick look, seems like the Dressrosa episodes use a different naming convention to the rest of the One Pace episodes. I haven't download and tested the later seasons yet - I just assumed would keep the same naming convention.

**Standard Season**: _[One Pace][1] Romance Dawn 01 [1080p][FB72C13F].mkv_     
**Dressrosa Season**: _[One Pace] Chapter 700-701 [720p][2A35B710].mkv_

The renaming script relies on the fact that the episodes are consistently named. The Dressrosa episodes are also missing their episode numbers which is a pain.

I'll see if I can find some time to fix this. Would probably need to make a workaround for this season in particular. There could be other seasons with different naming conventions too.

**Comment by tajlamont** [comment]
I thought that may have been the reason why.

I have from S27-34 (Wano) and they are all named in the standard name scheme you wrote before, so they work with the rename.exe.

Would there be a workaround for the moment? What would the exe be expecting the file name to be, and if I change them all to that, would it work?

**Comment by tajlamont** [comment]
@SpykerNZ That seems to have worked. Thanks for the quick fix man :)

**Comment by SpykerNZ** [comment]
Awesome! No worries. I will close this issue - if you find any other renaming inconsistencies feel free to open another one
