### ISSUE TITLE
Season 30-34 No update to naming

### ISSUE THREAD

**Issue by oldhats** [SpykerNZ/one-pace-for-plex#21]
I am on Windows and have all required files in my One Pace folder and each season, yet when running rename.py or using the executable, no update is shown.

**Comment by cawnj** [comment]
If you could provide some example filenames for a couple of the files you're having issues with I can help you debug the issue!

**Comment by oldhats** [comment]
([One Pace] Chapter 700-701 [720p][2A35B710].mkv) ([One Pace] Chapter 718-719 [720p][50143351]) Season 30-34 follows this naming convention. I saw a previous report having the same issue but theirs was resolved but had no luck on my end.

**Comment by cawnj** [comment]
Thanks for that! I have the exact same filename here and it's working as expected, can you check to make sure your folder structure looks like this:
```
└── One Pace
    ├── Season 30
    │   ├── One Pace - S30E01 - Arriving at Dressrosa! The Country of Passion, Love, and Toys!.nfo
    │   └── [One Pace] Chapter 700-701 [720p][2A35B710].mkv
    ├── exceptions.json
    ├── rename.py
    └── seasons.json
```

**Comment by oldhats** [comment]
My file structure looks the same i have the 3 required files in my One page folder and each individual season arc

**Comment by cawnj** [comment]
@oldhats Ok thanks, here's a couple more ideas:
- Are your season folders named correctly? "Season 30", "Season 31", etc.
- Is your Python version up-to-date? (or at least > Python 3.7)
- You can also try deleting and copying back the latest versions of rename.py, exceptions.json and seasons.json to ensure they are up-to-date

**Comment by oldhats** [comment]
Everything listed I have done but to no luck. Im gonna close this issue as I believe its on my part. Thanks for the help!
