### ISSUE TITLE
Is step "3. Download Missing One Piece Episodes" essential?

### ISSUE THREAD

**Issue by TheOne320** [SpykerNZ/one-pace-for-plex#48]
Like the title says, is step 3 absolutely needed? I only want to watch the Once Pace releases as the come out. Will something break if I do not download all missing episodes?

**Comment by TheIceCreamTroll** [comment]
You don't have to download the original One Piece episodes, they just cover the parts that One Pace hasn't gotten to yet. Nothing will break if you don't add them.

**Comment by TheOne320** [comment]
Thanks
