### ISSUE TITLE
Season numbering mismatch

### ISSUE THREAD

**Issue by monkTertman** [SpykerNZ/one-pace-for-plex#60]
### Description
According to the One Pace [episode spreadsheet](https://docs.google.com/spreadsheets/d/1HQRMJgu_zArp-sLnvFMDzOyjdsht87eFLECxMK858lA/) the season arc "The Adventures of Buggy's Crew", "The Trials of Koby-Meppo" and "The Adventures of the Straw Hats" do not have separate numbers but this project adds separate season numbers for them which messes up the entire season numbering.
It becomes hard to update the library and add episodes incrementally as they no longer have the same numbering as the spreadsheet. The folders also do not have the arc name and just the number which just adds to this obscurity.

### Possible solutions:
- Merge the episodes in the previous season arc instead of having separate seasons for them.
- As they are just single episodes, move them to the specials folder, and with the correct metadata for release date, they should automatically play next after the certain season ends.

**Comment by SpykerNZ** [comment]
This repo is not supposed to match the spreadsheet, but match the grouping of episodes on their official website. Thus I don't believe we need any changes made relating to these specials. They feel like they make sense as they are.

The numbering of the arc names can be seen in seasons.json if you want to quickly look anything up.

Shifting these episodes around also have the following implications:
- Existing users of this repo will have to restructure everything which is not ideal
- The season posters bundled in the repo will no longer match and need to be udpated

I will leave this open for any further discussion/opinions. Will close at a later date.

**Comment by Cook13s7777** [comment]
Do you have work arounds? I noticed with this way.. the season is completely missing using the original downloads from One Pace.

![image](https://github.com/user-attachments/assets/178ac673-bd31-423a-baef-bc832d01c814)

**Comment by SpykerNZ** [comment]
> original downloads from One Pace.

By this do you mean downloading directly from the website? After downloading from the website you should be putting the files in to a folder structure matching the season order.

You can check seasons.json to see the expected order of seasons & their respective numbers.

Do you have season 7 in your folder structure, with the episode present and renamed correctly?

**Comment by Cook13s7777** [comment]
I grabbed the direct links to the torrents/nzb’s that are on their release announcements. I didn’t rename them, they all seem to work fine except for the #.5 releases and the show poster. Up to season 12, I dropped each season into it’s respective folder (looked at each season NFO to make sure it matches.) The only thing I might have added are TVDB/IMDB ids to the show nfo. I can remove those if anything, not sure if that overrides the local metadata. I also added a .plex-match file (I think is the name), which contains just about the same info. How can I update the metadata myself so that it knows that the .5 seasons are matching the nfo (or viceversa)?

**Comment by Cook13s7777** [comment]
.plexmatch
`Title: One Pace
Year: 2017
TvdbId: 335179
ImdbId: tt31228002
`
tvshow.nfo
`
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<tvshow>
  <title>One Pace</title>
  <originaltitle/>
  <showtitle>One Pace</showtitle>
  <sorttitle/>
  <year>2017<year/>
  <ratings/>
  <userrating>0.0</userrating>
  <outline/>
  <plot/>
  <tagline/>
  <runtime>0</runtime>
  <namedseason number="1">1. Romance Dawn</namedseason>
  <namedseason number="2">2. Orange Town</namedseason>
  <namedseason number="3">3. Syrup Village</namedseason>
  <namedseason number="4">4. Gaimon</namedseason>
  <namedseason number="5">5. Baratie</namedseason>
  <namedseason number="6">6. Arlong Park</namedseason>
  <namedseason number="7">7. The Adventures of Buggy's Crew</namedseason>
  <namedseason number="8">8. Loguetown</namedseason>
  <namedseason number="9">9. Reverse Mountain</namedseason>
  <namedseason number="10">10. Whisky Peak</namedseason>
  <namedseason number="11">11. The Trials of Koby Meppo</namedseason>
  <namedseason number="12">12. Little Garden</namedseason>
  <namedseason number="13">13. Drum Island</namedseason>
  <namedseason number="14">14. Arabasta</namedseason>
  <namedseason number="15">15. Jaya</namedseason>
  <namedseason number="16">16. Skypiea</namedseason>
  <namedseason number="17">17. Long Ring Long Land</namedseason>
  <namedseason number="18">18. Water Seven</namedseason>
  <namedseason number="19">19. Enies Lobby</namedseason>
  <namedseason number="20">20. Post-Enies Lobby</namedseason>
  <namedseason number="21">21. Thriller Bark</namedseason>
  <namedseason number="22">22. Sabaody Archipelago</namedseason>
  <namedseason number="23">23. Amazon Lily</namedseason>
  <namedseason number="24">24. Impel Down</namedseason>
  <namedseason number="25">25. If You Could Go Anywhere... The Adventures of the Straw Hats</namedseason>
  <namedseason number="26">25. Marineford</namedseason>
  <namedseason number="27">26. Post-War</namedseason>
  <namedseason number="26">27. Return to Sabaody</namedseason>
  <namedseason number="29">28. Fishman Island</namedseason>
  <namedseason number="30">29. Punk Hazard</namedseason>
  <namedseason number="31">30. Dressrosa</namedseason>
  <namedseason number="32">31. Zou</namedseason>
  <namedseason number="33">32. Whole Cake Island</namedseason>
  <namedseason number="34">33. Reverie</namedseason>
  <namedseason number="35">34. Wano</namedseason>
  <namedseason number="36">36. Egghead</namedseason>
  <mpaa/>
  <certification/>
  <episodeguide>{}</episodeguide>
  <id/>
  <imdbid>tt31228002<imdbid/>
  <tmdbid>335179<tmdbid/>
  <premiered/>
  <status>Unknown</status>
  <watched>false</watched>
  <playcount/>
  <studio/>
  <country/>
  <trailer/>
  <dateadded>2023-08-23 18:17:40</dateadded>
  
  <user_note/>
</tvshow>
`

As you can see the episode .nfo's are untouched. Based on my screenshots below.
![explorer_XfumJ1zqFW](https://github.com/user-attachments/assets/9b124063-0488-4923-ac62-23eea935baf6)
![explorer_BpBURQ4dLY](https://github.com/user-attachments/assets/23b52a57-8cf5-45df-90ba-d27d1aea4b51)

`
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<episodedetails>
  <title>Live</title>
  <originaltitle/>
  <showtitle>One Pace</showtitle>
  <season>6</season>
  <episode>5</episode>
  <displayseason>-1</displayseason>
  <displayepisode>-1</displayepisode>
  <id/>
  <ratings/>
  <userrating>0.0</userrating>
  <plot>When a Navy officer under Arlong's pay confiscates all the money Nami accumulated over the years, it becomes clear where Arlong stands on his promise.

Manga Chapter(s): 79-81

Anime Episode(s): 36-37</plot>
  <runtime>0</runtime>
  <mpaa/>
  <premiered>2020-05-07</premiered>
  <aired>2020-05-07</aired>
  <watched>false</watched>
  <playcount>0</playcount>
  <trailer/>
  <dateadded>2023-08-23 21:34:50</dateadded>
  <epbookmark/>
  <code/>
  <fileinfo>
    <streamdetails>
      <video>
        <codec>HEVC</codec>
        <aspect>1.33</aspect>
        <width>640</width>
        <height>480</height>
        <durationinseconds>1863</durationinseconds>
        <stereomode/>
      </video>
      <audio>
        <codec>AAC</codec>
        <language>jpn</language>
        <channels>2</channels>
      </audio>
      <audio>
        <codec>AAC</codec>
        <language>eng</language>
        <channels>2</channels>
      </audio>
      <subtitle>
        <language>eng</language>
      </subtitle>
      <subtitle>
        <language>eng</language>
      </subtitle>
      <subtitle>
        <language>spa</language>
      </subtitle>
    </streamdetails>
  </fileinfo>
  
  <source>UNKNOWN</source>
  <original_filename>One Pace - S06E05 - Live.mkv</original_filename>
  <user_note/>
</episodedetails>
`

`
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<episodedetails>
  <title>The Adventures of Buggy's Crew</title>
  <originaltitle/>
  <showtitle>One Pace</showtitle>
  <season>7</season>
  <episode>1</episode>
  <displayseason>-1</displayseason>
  <displayepisode>-1</displayepisode>
  <id/>
  <ratings/>
  <userrating>0.0</userrating>
  <plot>Buggy, after being defeated by Luffy, Zoro, and Nami, begins his quest to regain his body parts and his crew, and then he will get his flashy revenge on Luffy.&#13;
&#13;
Manga Chapter(s): 35-75 cover stories&#13;
&#13;
Anime Episode(s): 46-47</plot>
  <runtime>0</runtime>
  <mpaa/>
  <premiered>2023-10-06</premiered>
  <aired>2023-10-06</aired>
  <watched>false</watched>
  <playcount>0</playcount>
  <trailer/>
  <dateadded>2023-10-06 11:02:45</dateadded>
  <epbookmark/>
  <code/>
  <fileinfo>
    <streamdetails>
      <video>
        <codec>HEVC</codec>
        <aspect>1.33</aspect>
        <width>1440</width>
        <height>1080</height>
        <durationinseconds>1346</durationinseconds>
        <stereomode/>
      </video>
      <audio>
        <codec>AAC</codec>
        <language>jpn</language>
        <channels>2</channels>
      </audio>
      <audio>
        <codec>AAC</codec>
        <language>eng</language>
        <channels>2</channels>
      </audio>
      <subtitle>
        <language>eng</language>
      </subtitle>
      <subtitle>
        <language>eng</language>
      </subtitle>
      <subtitle>
        <language>spa</language>
      </subtitle>
      <subtitle>
        <language>fre</language>
      </subtitle>
    </streamdetails>
  </fileinfo>
  
  <source>UNKNOWN</source>
  <original_filename>One Pace - S07E01 - The Adventures of Buggy's Crew.mkv</original_filename>
  <user_note/>
</episodedetails>
`

**Comment by SpykerNZ** [comment]
Thanks for the detailed comment <3

Renaming the video files ensures that the .nfo files are matched exactly. If they have the exact same name Plex should pick them up. From your post they seem to be picked up under other conditions, but haven't dug into that.

**Comment by Cook13s7777** [comment]
> Thanks for the detailed comment <3
You’re welcome, just trying to get to the bottom  of things.

> Renaming the video files ensures that the .nfo files are matched exactly. If they have the exact same name Plex should pick them up. From your post they seem to be picked up under other conditions, but haven't dug into that.
So a question about that, if I wanted to do the reverse myself, what is the episode .nfo field or attribute that it’s using to match? I think I want to try updating the .nfo itself instead of renaming the episode. I just want to test if the ID works instead of the name.

**Comment by SpykerNZ** [comment]
Closing this thread since no further discussion has been made on the original topic. Can re-open a new topic if anyone has further concerns.

**Comment by Cook13s7777** [comment]
I don’t think I got an answer for my question. I’ve figured it out anyway on my own which is the “original_filename” attribute but apparently copying the pace filename to that attribute doesn’t work well. So I rename it to something simple without the codes or bracketed ID references. That seemed to have worked.Sent from my iPhoneOn Sep 7, 2024, at 5:52 AM, Jamie Spyker ***@***.***> wrote:﻿
Closed #60 as completed.
